name: share_handler_platform_interface
description: A common platform interface for the share_handler plugin.
repository: https://github.com/AboutShout/share_handler/tree/main/share_handler_platform_interface
version: 0.0.6

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_lints:
