name: share_handler
description: A Flutter plugin to handle incoming shared text/media, as well as add share to suggestions/shortcuts.
repository: https://github.com/AboutShout/share_handler/tree/main/share_handler
version: 0.0.16

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms: 
      android:
        default_package: share_handler_android 
      ios:
        default_package: share_handler_ios 
      # linux:
      #   default_package: share_handler_linux 
      # macos:
      #   default_package: share_handler_macos 
      # web:
      #   default_package: share_handler_web 
      # windows:
      #   default_package: share_handler_windows 

dependencies:
  flutter:
    sdk: flutter
  share_handler_android: ^0.0.6
  # share_handler_android:
  #   path: ../share_handler_android
  share_handler_ios: ^0.0.9
  # share_handler_ios:
  #   path: ../share_handler_ios
  # share_handler_linux:
  #   path: ../share_handler_linux 
  # share_handler_macos:
  #   path: ../share_handler_macos 
  # share_handler_web:
  #   path: ../share_handler_web 
  # share_handler_windows:
  #   path: ../share_handler_windows 
  share_handler_platform_interface: ^0.0.4
  # share_handler_platform_interface:
  #   path: ../share_handler_platform_interface

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  plugin_platform_interface: ^2.0.1
